# Datasource's configurations for PostgresSQL
spring.datasource.url = jdbc:postgresql://localhost:5432/AFTAS
spring.datasource.username = postgres
spring.datasource.password = 1234

# Hibernate's configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Springboot configuration
server.port=8080
server.address=0.0.0.0